apiVersion: v1
kind: Service
metadata:
  name: chess-ecosystem-frontend
  labels:
    app: chess-ecosystem
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: chess-ecosystem
    component: frontend
